name: example
description: A sample command-line application.
version: 2.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator:
    path: ../../packages/envied_generator
  lints: ^2.1.1
  test: ^1.24.6
dependencies:
  envied: 
    path: ../../packages/envied

